CREATE TABLE [dbo].[Companies]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL PRIMARY KEY,
	[CompanyId] INT UNIQUE IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[NipNumber] INT NOT NULL
)