CREATE TABLE [dbo].[Managers]
(
    [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL PRIMARY KEY,
	[ManagerId] INT UNIQUE IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[Surname] VARCHAR(50) NOT NULL
)
