CREATE TABLE [dbo].[Tasks]
(
    [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL PRIMARY KEY,
    [TaskId] INT UNIQUE IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(200) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Owner] UNIQUEIDENTIFIER NOT NULL,
    [Shared] BIT NOT NULL,
    [Priority] INT NOT NULL,
    [StoryPointsEstimation] INT NULL
);
