CREATE TABLE [dbo].[Tasks]
(
	[Id] UNIQUEIDENTIFIER UNIQUE DEFAULT NEWSEQUENTALID() NOT NULL,
	[TaskId] INT UNIQUE IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(200) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	[Owner] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Workers(Id) NULL,
	[StoryPointsEstimation] INT NULL
)
