CREATE TABLE [dbo].[Workers]
(
    [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL PRIMARY KEY,
	[WorkerId] INT UNIQUE IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[Surname] VARCHAR(50) NOT NULL,
	[ManagerId] UNIQUEIDENTIFIER NOT NULL
)
