CREATE TABLE [dbo].[Workers]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Surname] VARCHAR(50) NOT NULL,
	[GroupsOfWorkers] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Managers(Id) NOT NULL
)
